version: '3.8'

services:
  cafe-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cafe-management
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
